#############################################################################
# Makefile for building: qviewer
# Generated by qmake (2.01a) (Qt 4.8.7) on: Mon Oct 11 13:12:13 2021
# Project:  qviewer.pro
# Template: subdirs
# Command: /usr/local/bin/qmake -o Makefile qviewer.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/local/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-libgq \
		sub-demoutils \
		sub-qglviewer \
		sub-trimesh2 \
		sub-qviewer

libgq/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libgq/ || $(MKDIR) libgq/ 
	cd libgq/ && $(QMAKE) /Users/viviehn/Research/qrtsc/libgq/libgq.pro -o $(MAKEFILE)
sub-libgq-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libgq/ || $(MKDIR) libgq/ 
	cd libgq/ && $(QMAKE) /Users/viviehn/Research/qrtsc/libgq/libgq.pro -o $(MAKEFILE)
sub-libgq: libgq/$(MAKEFILE) FORCE
	cd libgq/ && $(MAKE) -f $(MAKEFILE)
sub-libgq-make_default-ordered: libgq/$(MAKEFILE) FORCE
	cd libgq/ && $(MAKE) -f $(MAKEFILE) 
sub-libgq-make_default: libgq/$(MAKEFILE) FORCE
	cd libgq/ && $(MAKE) -f $(MAKEFILE) 
sub-libgq-make_first-ordered: libgq/$(MAKEFILE) FORCE
	cd libgq/ && $(MAKE) -f $(MAKEFILE) first
sub-libgq-make_first: libgq/$(MAKEFILE) FORCE
	cd libgq/ && $(MAKE) -f $(MAKEFILE) first
sub-libgq-all-ordered: libgq/$(MAKEFILE) FORCE
	cd libgq/ && $(MAKE) -f $(MAKEFILE) all
sub-libgq-all: libgq/$(MAKEFILE) FORCE
	cd libgq/ && $(MAKE) -f $(MAKEFILE) all
sub-libgq-clean-ordered: libgq/$(MAKEFILE) FORCE
	cd libgq/ && $(MAKE) -f $(MAKEFILE) clean
sub-libgq-clean: libgq/$(MAKEFILE) FORCE
	cd libgq/ && $(MAKE) -f $(MAKEFILE) clean
sub-libgq-distclean-ordered: libgq/$(MAKEFILE) FORCE
	cd libgq/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libgq-distclean: libgq/$(MAKEFILE) FORCE
	cd libgq/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libgq-install_subtargets-ordered: libgq/$(MAKEFILE) FORCE
	cd libgq/ && $(MAKE) -f $(MAKEFILE) install
sub-libgq-install_subtargets: libgq/$(MAKEFILE) FORCE
	cd libgq/ && $(MAKE) -f $(MAKEFILE) install
sub-libgq-uninstall_subtargets-ordered: libgq/$(MAKEFILE) FORCE
	cd libgq/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-libgq-uninstall_subtargets: libgq/$(MAKEFILE) FORCE
	cd libgq/ && $(MAKE) -f $(MAKEFILE) uninstall
demoutils/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) demoutils/ || $(MKDIR) demoutils/ 
	cd demoutils/ && $(QMAKE) /Users/viviehn/Research/qrtsc/demoutils/demoutils.pro -o $(MAKEFILE)
sub-demoutils-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) demoutils/ || $(MKDIR) demoutils/ 
	cd demoutils/ && $(QMAKE) /Users/viviehn/Research/qrtsc/demoutils/demoutils.pro -o $(MAKEFILE)
sub-demoutils: demoutils/$(MAKEFILE) FORCE
	cd demoutils/ && $(MAKE) -f $(MAKEFILE)
sub-demoutils-make_default-ordered: demoutils/$(MAKEFILE) sub-libgq-make_default-ordered  FORCE
	cd demoutils/ && $(MAKE) -f $(MAKEFILE) 
sub-demoutils-make_default: demoutils/$(MAKEFILE) FORCE
	cd demoutils/ && $(MAKE) -f $(MAKEFILE) 
sub-demoutils-make_first-ordered: demoutils/$(MAKEFILE) sub-libgq-make_first-ordered  FORCE
	cd demoutils/ && $(MAKE) -f $(MAKEFILE) first
sub-demoutils-make_first: demoutils/$(MAKEFILE) FORCE
	cd demoutils/ && $(MAKE) -f $(MAKEFILE) first
sub-demoutils-all-ordered: demoutils/$(MAKEFILE) sub-libgq-all-ordered  FORCE
	cd demoutils/ && $(MAKE) -f $(MAKEFILE) all
sub-demoutils-all: demoutils/$(MAKEFILE) FORCE
	cd demoutils/ && $(MAKE) -f $(MAKEFILE) all
sub-demoutils-clean-ordered: demoutils/$(MAKEFILE) sub-libgq-clean-ordered  FORCE
	cd demoutils/ && $(MAKE) -f $(MAKEFILE) clean
sub-demoutils-clean: demoutils/$(MAKEFILE) FORCE
	cd demoutils/ && $(MAKE) -f $(MAKEFILE) clean
sub-demoutils-distclean-ordered: demoutils/$(MAKEFILE) sub-libgq-distclean-ordered  FORCE
	cd demoutils/ && $(MAKE) -f $(MAKEFILE) distclean
sub-demoutils-distclean: demoutils/$(MAKEFILE) FORCE
	cd demoutils/ && $(MAKE) -f $(MAKEFILE) distclean
sub-demoutils-install_subtargets-ordered: demoutils/$(MAKEFILE) sub-libgq-install_subtargets-ordered  FORCE
	cd demoutils/ && $(MAKE) -f $(MAKEFILE) install
sub-demoutils-install_subtargets: demoutils/$(MAKEFILE) FORCE
	cd demoutils/ && $(MAKE) -f $(MAKEFILE) install
sub-demoutils-uninstall_subtargets-ordered: demoutils/$(MAKEFILE) sub-libgq-uninstall_subtargets-ordered  FORCE
	cd demoutils/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-demoutils-uninstall_subtargets: demoutils/$(MAKEFILE) FORCE
	cd demoutils/ && $(MAKE) -f $(MAKEFILE) uninstall
qglviewer/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qglviewer/ || $(MKDIR) qglviewer/ 
	cd qglviewer/ && $(QMAKE) /Users/viviehn/Research/qrtsc/qglviewer/qglviewer.pro -o $(MAKEFILE)
sub-qglviewer-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qglviewer/ || $(MKDIR) qglviewer/ 
	cd qglviewer/ && $(QMAKE) /Users/viviehn/Research/qrtsc/qglviewer/qglviewer.pro -o $(MAKEFILE)
sub-qglviewer: qglviewer/$(MAKEFILE) FORCE
	cd qglviewer/ && $(MAKE) -f $(MAKEFILE)
sub-qglviewer-make_default-ordered: qglviewer/$(MAKEFILE) sub-demoutils-make_default-ordered  FORCE
	cd qglviewer/ && $(MAKE) -f $(MAKEFILE) 
sub-qglviewer-make_default: qglviewer/$(MAKEFILE) FORCE
	cd qglviewer/ && $(MAKE) -f $(MAKEFILE) 
sub-qglviewer-make_first-ordered: qglviewer/$(MAKEFILE) sub-demoutils-make_first-ordered  FORCE
	cd qglviewer/ && $(MAKE) -f $(MAKEFILE) first
sub-qglviewer-make_first: qglviewer/$(MAKEFILE) FORCE
	cd qglviewer/ && $(MAKE) -f $(MAKEFILE) first
sub-qglviewer-all-ordered: qglviewer/$(MAKEFILE) sub-demoutils-all-ordered  FORCE
	cd qglviewer/ && $(MAKE) -f $(MAKEFILE) all
sub-qglviewer-all: qglviewer/$(MAKEFILE) FORCE
	cd qglviewer/ && $(MAKE) -f $(MAKEFILE) all
sub-qglviewer-clean-ordered: qglviewer/$(MAKEFILE) sub-demoutils-clean-ordered  FORCE
	cd qglviewer/ && $(MAKE) -f $(MAKEFILE) clean
sub-qglviewer-clean: qglviewer/$(MAKEFILE) FORCE
	cd qglviewer/ && $(MAKE) -f $(MAKEFILE) clean
sub-qglviewer-distclean-ordered: qglviewer/$(MAKEFILE) sub-demoutils-distclean-ordered  FORCE
	cd qglviewer/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qglviewer-distclean: qglviewer/$(MAKEFILE) FORCE
	cd qglviewer/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qglviewer-install_subtargets-ordered: qglviewer/$(MAKEFILE) sub-demoutils-install_subtargets-ordered  FORCE
	cd qglviewer/ && $(MAKE) -f $(MAKEFILE) install
sub-qglviewer-install_subtargets: qglviewer/$(MAKEFILE) FORCE
	cd qglviewer/ && $(MAKE) -f $(MAKEFILE) install
sub-qglviewer-uninstall_subtargets-ordered: qglviewer/$(MAKEFILE) sub-demoutils-uninstall_subtargets-ordered  FORCE
	cd qglviewer/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-qglviewer-uninstall_subtargets: qglviewer/$(MAKEFILE) FORCE
	cd qglviewer/ && $(MAKE) -f $(MAKEFILE) uninstall
trimesh2/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) trimesh2/ || $(MKDIR) trimesh2/ 
	cd trimesh2/ && $(QMAKE) /Users/viviehn/Research/qrtsc/trimesh2/trimesh2.pro -o $(MAKEFILE)
sub-trimesh2-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) trimesh2/ || $(MKDIR) trimesh2/ 
	cd trimesh2/ && $(QMAKE) /Users/viviehn/Research/qrtsc/trimesh2/trimesh2.pro -o $(MAKEFILE)
sub-trimesh2: trimesh2/$(MAKEFILE) FORCE
	cd trimesh2/ && $(MAKE) -f $(MAKEFILE)
sub-trimesh2-make_default-ordered: trimesh2/$(MAKEFILE) sub-qglviewer-make_default-ordered  FORCE
	cd trimesh2/ && $(MAKE) -f $(MAKEFILE) 
sub-trimesh2-make_default: trimesh2/$(MAKEFILE) FORCE
	cd trimesh2/ && $(MAKE) -f $(MAKEFILE) 
sub-trimesh2-make_first-ordered: trimesh2/$(MAKEFILE) sub-qglviewer-make_first-ordered  FORCE
	cd trimesh2/ && $(MAKE) -f $(MAKEFILE) first
sub-trimesh2-make_first: trimesh2/$(MAKEFILE) FORCE
	cd trimesh2/ && $(MAKE) -f $(MAKEFILE) first
sub-trimesh2-all-ordered: trimesh2/$(MAKEFILE) sub-qglviewer-all-ordered  FORCE
	cd trimesh2/ && $(MAKE) -f $(MAKEFILE) all
sub-trimesh2-all: trimesh2/$(MAKEFILE) FORCE
	cd trimesh2/ && $(MAKE) -f $(MAKEFILE) all
sub-trimesh2-clean-ordered: trimesh2/$(MAKEFILE) sub-qglviewer-clean-ordered  FORCE
	cd trimesh2/ && $(MAKE) -f $(MAKEFILE) clean
sub-trimesh2-clean: trimesh2/$(MAKEFILE) FORCE
	cd trimesh2/ && $(MAKE) -f $(MAKEFILE) clean
sub-trimesh2-distclean-ordered: trimesh2/$(MAKEFILE) sub-qglviewer-distclean-ordered  FORCE
	cd trimesh2/ && $(MAKE) -f $(MAKEFILE) distclean
sub-trimesh2-distclean: trimesh2/$(MAKEFILE) FORCE
	cd trimesh2/ && $(MAKE) -f $(MAKEFILE) distclean
sub-trimesh2-install_subtargets-ordered: trimesh2/$(MAKEFILE) sub-qglviewer-install_subtargets-ordered  FORCE
	cd trimesh2/ && $(MAKE) -f $(MAKEFILE) install
sub-trimesh2-install_subtargets: trimesh2/$(MAKEFILE) FORCE
	cd trimesh2/ && $(MAKE) -f $(MAKEFILE) install
sub-trimesh2-uninstall_subtargets-ordered: trimesh2/$(MAKEFILE) sub-qglviewer-uninstall_subtargets-ordered  FORCE
	cd trimesh2/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-trimesh2-uninstall_subtargets: trimesh2/$(MAKEFILE) FORCE
	cd trimesh2/ && $(MAKE) -f $(MAKEFILE) uninstall
qviewer/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) qviewer/ || $(MKDIR) qviewer/ 
	cd qviewer/ && $(QMAKE) /Users/viviehn/Research/qrtsc/qviewer/qviewer.pro -o $(MAKEFILE)
sub-qviewer-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) qviewer/ || $(MKDIR) qviewer/ 
	cd qviewer/ && $(QMAKE) /Users/viviehn/Research/qrtsc/qviewer/qviewer.pro -o $(MAKEFILE)
sub-qviewer: qviewer/$(MAKEFILE) FORCE
	cd qviewer/ && $(MAKE) -f $(MAKEFILE)
sub-qviewer-make_default-ordered: qviewer/$(MAKEFILE) sub-trimesh2-make_default-ordered  FORCE
	cd qviewer/ && $(MAKE) -f $(MAKEFILE) 
sub-qviewer-make_default: qviewer/$(MAKEFILE) FORCE
	cd qviewer/ && $(MAKE) -f $(MAKEFILE) 
sub-qviewer-make_first-ordered: qviewer/$(MAKEFILE) sub-trimesh2-make_first-ordered  FORCE
	cd qviewer/ && $(MAKE) -f $(MAKEFILE) first
sub-qviewer-make_first: qviewer/$(MAKEFILE) FORCE
	cd qviewer/ && $(MAKE) -f $(MAKEFILE) first
sub-qviewer-all-ordered: qviewer/$(MAKEFILE) sub-trimesh2-all-ordered  FORCE
	cd qviewer/ && $(MAKE) -f $(MAKEFILE) all
sub-qviewer-all: qviewer/$(MAKEFILE) FORCE
	cd qviewer/ && $(MAKE) -f $(MAKEFILE) all
sub-qviewer-clean-ordered: qviewer/$(MAKEFILE) sub-trimesh2-clean-ordered  FORCE
	cd qviewer/ && $(MAKE) -f $(MAKEFILE) clean
sub-qviewer-clean: qviewer/$(MAKEFILE) FORCE
	cd qviewer/ && $(MAKE) -f $(MAKEFILE) clean
sub-qviewer-distclean-ordered: qviewer/$(MAKEFILE) sub-trimesh2-distclean-ordered  FORCE
	cd qviewer/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qviewer-distclean: qviewer/$(MAKEFILE) FORCE
	cd qviewer/ && $(MAKE) -f $(MAKEFILE) distclean
sub-qviewer-install_subtargets-ordered: qviewer/$(MAKEFILE) sub-trimesh2-install_subtargets-ordered  FORCE
	cd qviewer/ && $(MAKE) -f $(MAKEFILE) install
sub-qviewer-install_subtargets: qviewer/$(MAKEFILE) FORCE
	cd qviewer/ && $(MAKE) -f $(MAKEFILE) install
sub-qviewer-uninstall_subtargets-ordered: qviewer/$(MAKEFILE) sub-trimesh2-uninstall_subtargets-ordered  FORCE
	cd qviewer/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-qviewer-uninstall_subtargets: qviewer/$(MAKEFILE) FORCE
	cd qviewer/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: qviewer.pro  /usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/unsupported/macx-clang-libc++/qmake.conf /usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/common/unix.conf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/common/mac.conf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/common/gcc-base.conf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/common/clang.conf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/qconfig.pri \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/qt_functions.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/qt_config.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/default_pre.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/mac/default_pre.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/release.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/default_post.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/mac/default_post.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/mac/x86_64.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/mac/objective_c.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/shared.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/warn_on.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/qt.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/unix/thread.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/moc.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/mac/rez.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/mac/sdk.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/resources.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/uic.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/yacc.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/lex.prf \
		/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile qviewer.pro
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/common/unix.conf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/common/mac.conf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/common/gcc-base.conf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/common/gcc-base-macx.conf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/common/clang.conf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/qconfig.pri:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/qt_functions.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/qt_config.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/exclusive_builds.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/default_pre.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/mac/default_pre.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/release.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/default_post.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/mac/default_post.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/mac/x86_64.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/mac/objective_c.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/shared.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/warn_on.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/qt.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/unix/thread.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/moc.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/mac/rez.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/mac/sdk.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/resources.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/uic.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/yacc.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/lex.prf:
/usr/local/Cellar/qt@4/4.8.7_6/etc/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile qviewer.pro

qmake_all: sub-libgq-qmake_all sub-demoutils-qmake_all sub-qglviewer-qmake_all sub-trimesh2-qmake_all sub-qviewer-qmake_all FORCE

make_default: sub-libgq-make_default-ordered sub-demoutils-make_default-ordered sub-qglviewer-make_default-ordered sub-trimesh2-make_default-ordered sub-qviewer-make_default-ordered FORCE
make_first: sub-libgq-make_first-ordered sub-demoutils-make_first-ordered sub-qglviewer-make_first-ordered sub-trimesh2-make_first-ordered sub-qviewer-make_first-ordered FORCE
all: sub-libgq-all-ordered sub-demoutils-all-ordered sub-qglviewer-all-ordered sub-trimesh2-all-ordered sub-qviewer-all-ordered FORCE
clean: sub-libgq-clean-ordered sub-demoutils-clean-ordered sub-qglviewer-clean-ordered sub-trimesh2-clean-ordered sub-qviewer-clean-ordered FORCE
distclean: sub-libgq-distclean-ordered sub-demoutils-distclean-ordered sub-qglviewer-distclean-ordered sub-trimesh2-distclean-ordered sub-qviewer-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-libgq-install_subtargets-ordered sub-demoutils-install_subtargets-ordered sub-qglviewer-install_subtargets-ordered sub-trimesh2-install_subtargets-ordered sub-qviewer-install_subtargets-ordered FORCE
uninstall_subtargets: sub-libgq-uninstall_subtargets-ordered sub-demoutils-uninstall_subtargets-ordered sub-qglviewer-uninstall_subtargets-ordered sub-trimesh2-uninstall_subtargets-ordered sub-qviewer-uninstall_subtargets-ordered FORCE

sub-libgq-check_ordered: libgq/$(MAKEFILE)
	cd libgq/ && $(MAKE) -f $(MAKEFILE) check
sub-demoutils-check_ordered: demoutils/$(MAKEFILE) sub-libgq-check_ordered 
	cd demoutils/ && $(MAKE) -f $(MAKEFILE) check
sub-qglviewer-check_ordered: qglviewer/$(MAKEFILE) sub-demoutils-check_ordered 
	cd qglviewer/ && $(MAKE) -f $(MAKEFILE) check
sub-trimesh2-check_ordered: trimesh2/$(MAKEFILE) sub-qglviewer-check_ordered 
	cd trimesh2/ && $(MAKE) -f $(MAKEFILE) check
sub-qviewer-check_ordered: qviewer/$(MAKEFILE) sub-trimesh2-check_ordered 
	cd qviewer/ && $(MAKE) -f $(MAKEFILE) check
check: sub-libgq-check_ordered sub-demoutils-check_ordered sub-qglviewer-check_ordered sub-trimesh2-check_ordered sub-qviewer-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

